# Generated by Django 5.1.4 on 2025-01-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_historicalad_historicalpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="description",
            field=models.TextField(default="Default Description", null=True),
        ),
        migrations.AlterField(
            model_name="historicalad",
            name="description",
            field=models.TextField(default="Default Description", null=True),
        ),
    ]
