# Generated by Django 5.1.4 on 2025-01-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_ad_description_alter_historicalad_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="description",
            field=models.TextField(default="Default Description"),
        ),
        migrations.AlterField(
            model_name="historicalad",
            name="description",
            field=models.TextField(default="Default Description"),
        ),
    ]
